baseURL = "https://wananaiko.design/"
title = "wananaiko"
paginate = 5
theme = "PaperModX"
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true

[params]
env = "production"
description = "Theme PaperModX - https://github.com/reorx/hugo-PaperModX"
author = [ "Reorx" ]
mainSections = [ "docs", "posts" ]
disableAnchoredHeadings = true
images = [ "cover.png" ]
DateFormat = "2006-01-02"
useCustomAnalytics = true
defaultTheme = "auto"
ShowShareButtons = true
ShowReadingTime = true
ShowWordCount = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowToc = true
TocOpen = true
TocSide = "right"
EnableInstantClick = false
EnableImageZoom = true

[params.commentSystems.disqus]
shortname = "reorx"

[params.commentSystems.remark42]
url = "https://remark42.reorx.com"
site = "reorx.github.io"

[params.commentSystems.telegramWidget]
channel = "reorx_share"
accentColor = "9077e1"
limit = 20

  [params.defaultCommentSystems]
  remark42 = true

  [params.profileMode]
  enabled = false
  title = "PaperModX"
  imageUrl = "#"
  imageTitle = "my image"

  [params.homeInfoParams]
  Title = "exPM, now UI/UX, currently learning FED."
  Content = """
<mark>Welcome to my blog!</mark>

 This is a platform for sharing knowledge about design, front-end, practical tools, daily learning and research. 

 Here you can find the latest trend information, technical articles, as well as experiences and skills shared by me and other industry experts. 

 I also provide the latest tutorials and practical tools to help you learn and improve your skills. 
 
 Welcome to share your thoughts, experiences and knowledge here, so that we can progress together!
"""

  [[params.socialIcons]]
  name = "github-simple"
  url = "https://github.com/wananaiko"

  [[params.socialIcons]]
  name = "rss-simple"
  url = "index.xml"

  [params.editPost]
  URL = "https://github.com/reorx/hugo-PaperModX/tree/exampleSite/content"
  Text = "Suggest Changes"
  appendFilePath = true

[minify]
disableXML = true

[languages.en]
languageName = "English"
weight = 1

[[languages.en.menu.main]]
name = "Blog"
url = "/docs/"
weight = 1

[[languages.en.menu.main]]
name = "Newsletter"
url = "/newsletter/"
weight = 4

[[languages.en.menu.main]]
name = "Memos"
url = "/memos/"
weight = 2

[[languages.en.menu.main]]
name = "Archive"
url = "/archives/"
weight = 3

[[languages.en.menu.main]]
name = "Search"
url = "/search/"
weight = 10

[[languages.en.menu.main]]
name = "@Author"
url = "https://reorx.com"

  [languages.en.menu.main.params]
  external = true

[languages.zh]
languageName = ":cn:"
languageAltTitle = "‰∏≠Êñá"
weight = 2
title = "PaperModX"

  [languages.zh.profileMode]
  enabled = true
  title = "PaperModX"
  subtitle = """
<p>Hugo ‰∏ªÈ¢ò</p> ‚òÑÔ∏è Âø´ÈÄü | ‚òÅÔ∏è ÊµÅÁïÖ | üìñ ÂèØËØªÊÄß | üì± ÂìçÂ∫îÂºè
"""

    [[languages.zh.profileMode.buttons]]
    name = "ÊñáÊ°£"
    url = "docs"

    [[languages.zh.profileMode.buttons]]
    name = "Ê†áÁ≠æ"
    url = "tags"

[[languages.zh.menu.main]]
name = "ÊñáÊ°£"
url = "docs"
weight = 1

[[languages.zh.menu.main]]
name = "Ê†áÁ≠æ"
url = "tags/"
weight = 4

[[languages.zh.menu.main]]
name = "ÂΩíÊ°£"
url = "archives"
weight = 5

[[languages.zh.menu.main]]
name = "ÊêúÁ¥¢"
url = "search/"
weight = 10

[[languages.zh.menu.main]]
name = "@‰ΩúËÄÖ"
url = "https://reorx.com"

  [languages.zh.menu.main.params]
  external = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "dracula"
lineNos = false
noClasses = false

[privacy.vimeo]
disabled = false
simple = true

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true
