baseURL = "https://wananaiko.com/"
title = "wananaiko"
paginate = 8
theme = "PaperModX"
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
hasCJKLanguage = true

[params]
env = "production"
description = "Design loser,slack off champion."
author = "wananaiko"
mainSections = [ "docs", "posts" ]
disableAnchoredHeadings = true
images = [ "cover.png" ]
favicon = "https://images.wananaiko.com/favicon.ico"
DateFormat = "2006-01-02"
useCustomAnalytics = true
defaultTheme = "auto"
ShowAuthor = false
ShowShareButtons = true
ShowReadingTime = true
ShowWordCount = false
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = false
ShowCodeCopyButtons = true
ShowToc = true
TocOpen = true
TocSide = "right"
EnableInstantClick = false
EnableImageZoom = true
hideMeta = false
comments = false


  [params.logo]
  icon = "images/forge-v2-compat.svg"

  [params.profileMode]
  enabled = false
  title = "PaperModX"
  imageUrl = "#"
  imageTitle = "my image"

  [params.homeInfoParams]
  Title = "Hi ğŸ‘‹"
  Content = """

  Welcome to my Island.
  
  About me, exPM, now UI/UX, learning Frontend, living in Shanghai.

  Iâ€™m writing here to share what I read and learned.
"""

  [[params.socialIcons]]
  name = "github-simple"
  url = "https://github.com/wananaiko"

  [[params.socialIcons]]
  name = "rss-simple"
  url = "index.xml"

  [[params.socialIcons]]
  name = "gmail"
  url = "mailto:7144206@qq.com"

  [[params.socialIcons]]
  name = "telegram-simple"
  url = "https://t.me/wananaiko"

  [params.editPost]
  URL = "https://github.com/reorx/hugo-PaperModX/tree/exampleSite/content"
  Text = "Suggest Changes"
  appendFilePath = true

[minify]
disableXML = true

[languages.en]
languageName = "English"
weight = 1

[[languages.en.menu.main]]
name = "Memos"
url = "/memos/"
weight = 1

[[languages.en.menu.main]]
name = "Goods"
url = "/goods/"
weight = 2

[[languages.en.menu.main]]
name = "Stack"
url = "/stack/"
weight = 3

[[languages.en.menu.main]]
name = "Archive"
url = "/archives/"
weight = 4

[[languages.en.menu.main]]
name = "Links"
url = "/links/"
weight = 6

[languages.zh]
languageName = ":cn:"
languageAltTitle = "ä¸­æ–‡"
weight = 2
title = "PaperModX"

  [languages.zh.profileMode]
  enabled = true
  title = "PaperModX"
  subtitle = """
<p>Hugo ä¸»é¢˜</p> â˜„ï¸ å¿«é€Ÿ | â˜ï¸ æµç•… | ğŸ“– å¯è¯»æ€§ | ğŸ“± å“åº”å¼
"""

    [[languages.zh.profileMode.buttons]]
    name = "æ–‡æ¡£"
    url = "docs"

    [[languages.zh.profileMode.buttons]]
    name = "æ ‡ç­¾"
    url = "tags"

[[languages.zh.menu.main]]
name = "æ–‡æ¡£"
url = "docs"
weight = 1

[[languages.zh.menu.main]]
name = "æ ‡ç­¾"
url = "/tags/"
weight = 4

[[languages.zh.menu.main]]
name = "å½’æ¡£"
url = "archives"
weight = 5

[[languages.zh.menu.main]]
name = "æœç´¢"
url = "search/"
weight = 10

[[languages.zh.menu.main]]
name = "@ä½œè€…"
url = "https://wananaiko.com"

  [languages.zh.menu.main.params]
  external = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "dracula"
lineNos = false
noClasses = false

[privacy.vimeo]
disabled = false
simple = true

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true 

[commentSystems.disqus]
shortname = "reorx"

[commentSystems.remark42]
url = "https://remark42.wananaiko.com"
site = "wananaiko"

[commentSystems.telegramWidget]
channel = "reorx_share"
accentColor = "9077e1"
limit = 20

[defaultCommentSystems]
remark42 = true
