baseURL = "https://wananaiko.com/"
title = "wananaiko"
paginate = 8
theme = "PaperModX"
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
hasCJKLanguage = true

[params]
env = "production"
description = "Design loser,slack off champion."
author = "wananaiko"
mainSections = [ "docs", "posts" ]
disableAnchoredHeadings = true
images = [ "cover.png" ]
favicon = "https://images.wananaiko.com/favicon.ico"
DateFormat = "2006-01-02"
useCustomAnalytics = true
defaultTheme = "auto"
ShowAuthor = false
ShowShareButtons = true
ShowReadingTime = false
ShowWordCount = false
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = false
ShowCodeCopyButtons = true
ShowToc = false
TocOpen = true
TocSide = "right"
EnableInstantClick = false
EnableImageZoom = true
hideMeta = false
comments = false


  [params.logo]
  icon = "images/forge-v2-compat.svg"

  [params.profileMode]
  enabled = false
  title = "PaperModX"
  imageUrl = "#"
  imageTitle = "my image"

  [params.homeInfoParams]
  Title = "å—¨ ğŸ‘‹"
  Content = """

  æ¬¢è¿æ¥åˆ°è¿™é‡Œï½

  è¿™é‡Œå¤§éƒ¨åˆ†æ˜¯å…³äºå‰ç«¯ã€è®¾è®¡å’Œä¸€äº›æŠ€æœ¯è¾¹ç¼˜çš„å†…å®¹ã€‚çœ‹åˆ°å¥½ç©æœ‰è¶£çš„å†…å®¹ï¼Œå°±ä¼šåˆ†äº«åœ¨è¿™é‡Œã€‚

  å…³äºæˆ‘ï¼Œå‰äº§å“ç»ç†ï¼Œç°åœ¨æ˜¯ UI/UXï¼Œæ­£åœ¨å­¦ä¹ å‰ç«¯ä¸­ï¼Œç›®å‰ç”Ÿæ´»åœ¨ä¸Šæµ·ã€‚

  æ¬¢è¿åœ¨æœ¬åšå®¢ç•™è¨€éªšæ‰°ï½

"""

  [[params.socialIcons]]
  name = "rss-simple"
  url = "index.xml"

  [[params.socialIcons]]
  name = "gmail"
  url = "mailto:7144206@qq.com"

  [[params.socialIcons]]
  name = "telegram-simple"
  url = "https://t.me/wananaiko"

  [params.editPost]
  URL = "https://github.com/reorx/hugo-PaperModX/tree/exampleSite/content"
  Text = "Suggest Changes"
  appendFilePath = true

[minify]
disableXML = true

[languages.en]
languageName = "English"
weight = 1

[[languages.en.menu.main]]
name = "è¯´è¯´"
url = "/memos/"
weight = 2

[[languages.en.menu.main]]
name = "ç›¸å†Œ"
url = "/gallery/"
weight = 3

[[languages.en.menu.main]]
name = "å¥½ç‰©"
url = "/goods/"
weight = 4

[[languages.en.menu.main]]
name = "è½¯ä»¶"
url = "/stack/"
weight = 5

[[languages.en.menu.main]]
name = "ä¹¦ç­¾"
url = "/bookmark/"
weight = 6

[[languages.en.menu.main]]
name = "çº¿ç´¢"
url = "/readwise/"
weight = 7

[[languages.en.menu.main]]
name = "å½’æ¡£"
url = "/archives/"
weight = 8

[[languages.en.menu.main]]
name = "é‚»å±…"
url = "/links/"
weight = 9

[languages.zh]
languageName = ":cn:"
weight = 2
title = "PaperModX"

  [languages.zh.params]
  languagealttitle = "ä¸­æ–‡"

  [languages.zh.params.profileMode]
  enabled = true
  title = "PaperModX"
  subtitle = """
<p>Hugo ä¸»é¢˜</p> â˜„ï¸ å¿«é€Ÿ | â˜ï¸ æµç•… | ğŸ“– å¯è¯»æ€§ | ğŸ“± å“åº”å¼
"""

    [[languages.zh.params.profileMode.buttons]]
    name = "æ–‡æ¡£"
    url = "docs"

    [[languages.zh.params.profileMode.buttons]]
    name = "æ ‡ç­¾"
    url = "tags"

[[languages.zh.menu.main]]
name = "æ–‡æ¡£"
url = "docs"
weight = 1

[[languages.zh.menu.main]]
name = "æ ‡ç­¾"
url = "/tags/"
weight = 4

[[languages.zh.menu.main]]
name = "å½’æ¡£"
url = "archives"
weight = 5

[[languages.zh.menu.main]]
name = "æœç´¢"
url = "search/"
weight = 10

[[languages.zh.menu.main]]
name = "@ä½œè€…"
url = "https://wananaiko.com"

  [languages.zh.menu.main.params]
  external = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "dracula"
lineNos = false
noClasses = false

[privacy.vimeo]
disabled = false
simple = true

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true 

[commentSystems.disqus]
shortname = "reorx"

[commentSystems.remark42]
url = "https://remark42.wananaiko.com"
site = "wananaiko"

[commentSystems.telegramWidget]
channel = "reorx_share"
accentColor = "9077e1"
limit = 20

[defaultCommentSystems]
remark42 = true

[frontmatter]
  lastmod = ['lastmod', ':git', ':fileModTime', 'date', 'publishDate']