baseURL = "https://wananaiko.design/"
title = "wananaiko"
paginate = 8
theme = "PaperModX"
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true

[params]
env = "production"
description = "Design loser,slack off champion."
author = "wananaiko"
mainSections = [ "docs", "posts" ]
disableAnchoredHeadings = true
images = [ "cover.png" ]
favicon = "https://images.wananaiko.com/favicon.ico"
DateFormat = "2006-01-02"
useCustomAnalytics = true
defaultTheme = "auto"
ShowAuthor = false
ShowShareButtons = true
ShowReadingTime = true
ShowWordCount = false
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = false
ShowCodeCopyButtons = true
ShowToc = true
TocOpen = true
TocSide = "right"
EnableInstantClick = false
EnableImageZoom = true
hideMeta = false
comments = true

  [params.profileMode]
  enabled = false
  title = "PaperModX"
  imageUrl = "#"
  imageTitle = "my image"

  [params.homeInfoParams]
  Title = "exPM, now UI/UX, currently learning Frontend."
  Content = """
<mark>Welcome to my blog!</mark>

 This is a platform for sharing knowledge about design, frontend, practical tools, daily learning and research. 

 Here you can find the latest trend information, technical articles, as well as experiences and skills shared by me and other industry experts. 

 I also provide the latest tutorials and practical tools to help you learn and improve your skills. 
 
 Welcome to share your thoughts, experiences and knowledge here, so that we can progress together!
"""

  [[params.socialIcons]]
  name = "github-simple"
  url = "https://github.com/wananaiko"

  [[params.socialIcons]]
  name = "rss-simple"
  url = "index.xml"

  [params.editPost]
  URL = "https://github.com/reorx/hugo-PaperModX/tree/exampleSite/content"
  Text = "Suggest Changes"
  appendFilePath = true

[minify]
disableXML = true

[languages.en]
languageName = "English"
weight = 1

[[languages.en.menu.main]]
name = "Article"
url = "/docs/"
weight = 1

[[languages.en.menu.main]]
name = "Search"
url = "/search/"
weight = 4

[[languages.en.menu.main]]
name = "Memos"
url = "/memos/"
weight = 2

[[languages.en.menu.main]]
name = "Archive"
url = "/archives/"
weight = 3

[[languages.en.menu.main]]
name = "Links"
url = "/links/"
weight = 15

[languages.zh]
languageName = ":cn:"
languageAltTitle = "ä¸­æ–‡"
weight = 2
title = "PaperModX"

  [languages.zh.profileMode]
  enabled = true
  title = "PaperModX"
  subtitle = """
<p>Hugo ä¸»é¢˜</p> â˜„ï¸ å¿«é€Ÿ | â˜ï¸ æµç•… | ğŸ“– å¯è¯»æ€§ | ğŸ“± å“åº”å¼
"""

    [[languages.zh.profileMode.buttons]]
    name = "æ–‡æ¡£"
    url = "docs"

    [[languages.zh.profileMode.buttons]]
    name = "æ ‡ç­¾"
    url = "tags"

[[languages.zh.menu.main]]
name = "æ–‡æ¡£"
url = "docs"
weight = 1

[[languages.zh.menu.main]]
name = "æ ‡ç­¾"
url = "/tags/"
weight = 4

[[languages.zh.menu.main]]
name = "å½’æ¡£"
url = "archives"
weight = 5

[[languages.zh.menu.main]]
name = "æœç´¢"
url = "search/"
weight = 10

[[languages.zh.menu.main]]
name = "@ä½œè€…"
url = "https://wananaiko.com"

  [languages.zh.menu.main.params]
  external = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "dracula"
lineNos = false
noClasses = false

[privacy.vimeo]
disabled = false
simple = true

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true 

